### ISSUE TITLE
The Naive W8A8 Quantized model accuracy of medium size model (e.g opt-2.7b)

### ISSUE THREAD

**Issue by LiuShixing** [mit-han-lab/smoothquant#10]
I tried to use Naive W8A8 method (quantize_model method only, dynamic scale) to quantize a 2.9 b gpt model，and found that the ppl is 15.1 which is closed to fp16 ppl (14.6).  In your smoothquant_opt_demo.ipynb, the Naive W8A8 accuracy is very slow. Is this because of dynamics quantization? 

Thank you very much.

**Comment by LiuShixing** [comment]
I have found relative results from your paper

**Comment by LiuShixing** [comment]
I have found relative results of your paper
![image](https://user-images.githubusercontent.com/14970396/206994024-cad790c3-75b3-49e5-b02e-0e266557c5de.png)
![image](https://user-images.githubusercontent.com/14970396/206995749-730954ee-10e5-4b0d-baae-c5f281f5cb7d.png)
Have you tried using static quantization for W8A8

**Comment by Guangxuan-Xiao** [comment]
In our paper, the W8A8 setting uses dynamic activation quantization (Table 3). Generally speaking, static quantization should be lossier than dynamic quantization.

> In your smoothquant_opt_demo.ipynb, the Naive W8A8 accuracy is very slow. Is this because of dynamics quantization?

I am not sure what you mean by the quantizer **slow** here. I assume you mean the large accuracy degradation? In the smoothquant_opt_demo.ipynb notebook, we use OPT-13B model to show the accuracy degradation of the W8A8 method. You can replace the model_name with `facebook/opt-2.7b` to check the performance of the naive baseline on the 2.7B model. From my side, the naive W8A8 method does work pretty well on the opt-2.7B model.

<img width="513" alt="Screenshot 2022-12-12 at 1 25 47 PM" src="https://user-images.githubusercontent.com/40906949/207124627-64349712-74cb-4305-ad4c-ea04d8e8c1a2.png">

<img width="513" alt="Screenshot 2022-12-12 at 1 25 57 PM" src="https://user-images.githubusercontent.com/40906949/207124662-7de4c277-c8d5-4228-ac20-b02468cb839f.png">
