### ISSUE TITLE
paper says smoothing all linear layers, but code seems to smooth only the qkv projection in attention and the first fc in ffn?

### ISSUE THREAD

**Issue by chenho74** [mit-han-lab/smoothquant#15]
In the `smooth_lm` function that is used to export int8 model, only the qkv projection layer and the first fc layer in FFN module go through the smoothing-based-on-range process, where the scaling of input is merged to the layernom before the linear layer, and the scaling of weights is merged to the weights of the linear layer. 
https://github.com/mit-han-lab/smoothquant/blob/be3c4239d21be5eeba7cd425a747c0d9c08804f6/smoothquant/smooth.py#L34

How about for the second linear layer of attention and FFN module? They don't have a layernom before it, how is the scaling of input implemented? Pointer to the code will be appreciated!

**Comment by erichan1** [comment]
Not the author, but looks like they loop through all the FCs? So we at least get the fc2. See [here](https://github.com/mit-han-lab/smoothquant/blob/be3c4239d21be5eeba7cd425a747c0d9c08804f6/smoothquant/smooth.py#L29).

**Comment by chenho74** [comment]
Yea exactly, only fc1 and qkv projection. No fc2 or attention output projection

**Comment by Guangxuan-Xiao** [comment]
I appreciate your interest in our project! On OPT and BLOOM models, we found that smoothing the QKV and FC1 two layers was sufficient to recover the accuracy. Smoothing `out_proj` in attention and FC2 in FFN is only necessary on GLM-130B, whose activations are more challenging to quantize. Thus we haven't included the code to smooth them in the current repo.

To smooth the `out_proj` in attention, you can divide the smoothing factors into the output channels of `v_proj`. And to smooth the FC2, we need to introduce another per-channel scaling before FC2.

**Comment by chenho74** [comment]
Thank you for the speedy clarification!

**Comment by fxmarty** [comment]
Interestingly the query scales are used for all the q_proj, k_proj, v_proj ops (fusing into the layernorm): https://github.com/mit-han-lab/smoothquant/blob/78badc0d975506de9fe44b2fe79d9a35d0fd4914/smoothquant/smooth.py#L40C36-L40C36
