### ISSUE TITLE
Calculating quantization scales for new models?

### ISSUE THREAD

**Issue by singularperturbation** [mit-han-lab/smoothquant#2]
I saw that you've uploaded activation scales (equation 4: $S_j = max(|X_j|) α / max(|W_j|)(1−α)$ ) for a number of models, but if calculating this for a new model, how do you use a calibration dataset when doing that? Do you take the maximum across all of the calibration values, or calculate the maximum for each value individually and then average?

Apologies if this will be addressed in soon-to-be-released code.

**Comment by Guangxuan-Xiao** [comment]
Thank you for your great question! In short, we use the maximum of maximums as activation channel scales. I have just released the calibration script to get those activation scales (https://github.com/mit-han-lab/smoothquant/blob/main/smoothquant/calibrate.py).
