### ISSUE TITLE
git lfs is currently down,could you solve this problem?

### ISSUE THREAD

**Issue by Anychnn** [mit-han-lab/smoothquant#31]
The idea is perfect, but i can't download scale file from git-lfs now~
Error downloading object: act_scales/bloom-176b.pt (83318e8): Smudge error: Error downloading act_scales/bloom-176b.pt (83318e8c5be645ed6ed606a9ad14502e81db8bfad980f3ec214822ba7e424866): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by lingffff** [comment]
Same problem. How do you solve it?
