### ISSUE TITLE
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

### ISSUE THREAD

**Issue by GuoYi0** [mit-han-lab/smoothquant#43]
There is an error when running at this line of code:
`act_scales = torch.load('../act_scales/opt-13b.pt')`
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by Guangxuan-Xiao** [comment]
Hi,

Thank you for raising this issue! We have uploaded our activation scales on [Huggingface](https://huggingface.co/mit-han-lab/smoothquant-scales).

Best,
Guangxuan
