### ISSUE TITLE
UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by FurryMushroom** [mit-han-lab/smoothquant#58]
When running act_scales = torch.load('../act_scales/opt-13b.pt') it reported error：

Traceback (most recent call last):
  File "/opt/TrySmooth/main.py", line 62, in <module>
    act_scales = torch.load('/opt/TrySmooth/act_scales/opt-13b.pt')
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

I wonder if there‘s anybody else encountered this error and wills to help.

**Comment by Louym** [comment]
I encountered the same error but don't have a solution yet.

**Comment by Alvant** [comment]
To use `'../act_scales/opt-13b.pt'`, one should do 'git lfs pull' first, but it is not possible :sweat_smile: (see issue https://github.com/mit-han-lab/smoothquant/issues/33)

**Comment by baiSongL** [comment]
I encountered the same error, how to solve this problem

**Comment by FurryMushroom** [comment]
Brother Alvant pointed out that this is already not solvable, it seems git lfs donnot allow such amount of data without the maintainer paying enough(out of quota). The act_scales might be generated by ourselves, and we can also refer to smoothquant-main\examples\smoothquant_opt_real_int8_demo.ipynb, which directly loads the quantized model and does evaluation both on accuarcy and latency. Isn't that more appealing?

**Comment by digbangbang** [comment]
> Alvant 兄弟指出，这已经无法解决，似乎 git lfs 不允许在维护者支付足够费用（超出配额）的情况下提供如此大量的数据。act_scales可能是我们自己生成的，我们也可以参考 smoothquant-main\examples\smoothquant_opt_real_int8_demo.ipynb，它直接加载量化模型，并对精度和延迟进行评估。这不是更吸引人吗？

Hi, furry
I have met the same problem.
When process the code `act_scales = torch.load('/lizhiwei/smoothquant/act_scales/opt-1.3b.pt')`
it comes out
UnpicklingError: invalid load key, 'v'.
 
So, does it mean that the smoothquant-main\examples\smoothquant_opt_demo.ipynb is not usable now? This demo is broken?

**Comment by SSshuishui** [comment]
Here I created a colab script based on the code of this project, using opt-1.3b for example.
https://colab.research.google.com/drive/1PP42K9OekoXfXpoXYDhrMUa_xdZY3XR9?usp=sharing

**Comment by Guangxuan-Xiao** [comment]
Hi,

Thank you for raising this issue! We have uploaded our activation scales on [Huggingface](https://huggingface.co/mit-han-lab/smoothquant-scales).

Best,
Guangxuan
