### ISSUE TITLE
Does it support freeze the quantized pretrained model then use prefix tuning ?

### ISSUE THREAD

**Issue by LiuShixing** [mit-han-lab/smoothquant#8]

**Comment by Guangxuan-Xiao** [comment]
Freezing a quantized pretrained model and using prefix tuning is a potentially exciting and worthwhile research question, but we have not tried it ourselves. There are two possible ways this could be implemented: 
1. using quantized weights and activations for the backward pass to calculate gradients on the soft prompts, but this could potentially lead to quantization error accumulation (both the forward and backward passes use quantized activations and weights), or 
2. using quantized weights and floating-point activations for the backward pass to calculate gradients on the soft prompts, which may be more accurate but would no longer allow the use of INT8 GEMM kernels in the backward pass.
